repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.3
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.1
    hooks:
      - id: mypy
        args: [--strict, --config-file=pyproject.toml, src, tests]
        pass_filenames: false
        additional_dependencies:
          [icontract==2.7.3, pydantic==2.12.4, pygame==2.6.1, pytest]
  - repo: local
    hooks:
      - id: fawltydeps
        name: fawltydeps
        entry: fawltydeps
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        types: [python]
      - id: interrogate
        name: interrogate
        entry: interrogate -c pyproject.toml src
        language: system
        pass_filenames: false
        types: [python]
