# from src.generator import *

from typing import Any

import customtkinter as ctk

class Configurator(ctk.CTk):  # type: ignore[misc]
    def __init__(self) -> None: ...
    def load_config(self, file_path: str) -> dict[str, Any]: ...
    def save_config(self, file_path: str) -> None: ...
    def get_config(self) -> dict[str, Any]: ...
