# from src.generator import *

import customtkinter as ctk

class Configurator(ctk.CTk):
    def __init__(self): ...
    def load_config(self, file_path: str) -> dict: ...
    def save_config(self, file_path: str) -> None: ...
    def get_config(self) -> dict: ...
