from configurator import Configurator
from tracked_array import Snapshot

class GUI:
    def __init__(self, width: int, height: int, config: Configurator) -> None: ...
    def draw(self, snapshot: Snapshot) -> None: ...
    def play_sound(self, value: int) -> None: ...
