from configurator import Configurator
from trackables import TrackedArray

class GUI:
    def __init__(self, width: int, height: int, config: Configurator) -> None: ...
    def draw(self, array: TrackedArray, highlights: list[int] = []) -> None: ...
    def play_sound(self, value: int) -> None: ...
