
class TrackedArray:
    def __init__(self, data: list[TrackedInteger]) -> None: ...
    def __getitem__(self, index: int) -> TrackedInteger: ...
    def __setitem__(self, index: int, value: TrackedInteger) -> None: ...
    def __len__(self) -> int: ...
    
class TrackedInteger(int):
    def __new__(cls, value: int) -> 'TrackedInteger': ...
    # to track comparisons
    def __gt__(self, value): ...
    def __lt__(self, value): ...
    def __eq__(self, value): ...
    